# Font
font_size        18.0

# Window
background_image ~/.config/kitty/background.png
background_image_layout scaled
background_image_linear yes
background_tint 0.9
background_opacity     0.99
background_blur        64
hide_window_decorations titlebar-only
window_padding_width   0 0 25 0
# macos_titlebar_color   background
macos_option_as_alt    yes

# Scrollback
scrollback_lines 10000
wheel_scroll_multiplier 3.0

# Cursor
cursor_shape           block
cursor_blink_interval  0

# Mouse
mouse_hide_wait 0

# Misc
enable_audio_bell no
window_alert_on_bell no
copy_on_select no

# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME

# BEGIN_KITTY_FONTS
font_family      family="Iosevka Term"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
