
* About
These are my dotfiles for everything I currently use or used to use.

* Screenshots and Posts
- [[https://www.reddit.com/r/emacs/comments/hnf3cw/my_orgmode_agenda_much_better_now_with_category/][My org-mode agenda, much better now with category icons!]]
- [[https://www.reddit.com/r/unixporn/comments/jprtoj/xmonad_productivity_workflow_emacs_orgmode_agenda/][xmonad Productivity workflow (Emacs org-mode agenda, Astroid notmuch email client)]]
- [[https://www.reddit.com/r/emacs/comments/moc6dw/my_orgagenda_on_my_phone/][My org-agenda on my phone]]

* Useful Shell Scripts
** [[file:bin/arbtt-running][arbtt-running]]
It displays [[https://arbtt.nomeata.de/#what][arbtt time tracker]]'s overall time spent today. Also if arbtt-capture is not running it displays a red alert showing OFF. It toggles arbtt-capture on or off on click (in i3blocks).

** [[file:bin/clocking][clocking]]
Displays the title  of current active (clocked) task in [[https://orgmode.org/][Org mode]] along with its Pomodoro counter and overall spent time. I use this in bars (polybar, awesomewm, i3blocks, etc).

** [[file:bin/reboot-p][reboot-p]]
Script to check if kernel needs a reboot to upgrade. I use this in bars to display REBOOT so that I know.
