" general {{{
syntax on
let g:vim_data_path = expand("$HOME") . "/.vim/data/"
" }}}


" shell {{{
set shell=/bin/bash
" }}}


" leader {{{
" let mapleader = ","
" let maplocalleader = "\\"
" }}}


" startup {{{
" vundle
set nocompatible  " be iMproved
filetype off      " required!

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

filetype plugin indent on     " required!


" other scripts
source ~/.vim/startup/options.vim
source ~/.vim/startup/plugins.vim
source ~/.vim/startup/mappings.vim
source ~/.vim/startup/autocmd.vim
source ~/.vim/startup/bundle.vim
source ~/.vim/startup/auto.vim
" }}}


" colorscheme {{{
colorscheme elflord
" }}}
