* Colemak HJKL contribution layer for Spacemacs
** Description
Remaps HJKL bindings used for navigation to JKHL, as they make more sense on a
[[http://colemak.com/][Colemak]] layout.

** Install
To use this contribution add it to your =~/.spacemacs=

#+begin_src emacs-lisp
  (setq-default dotspacemacs-configuration-layers '(colemak-hjkl))
#+end_src

** Key bindings
Most HJKL bindings bound by evil and Spacemacs are rebound to JKHL (L is thus
unchanged).

There is one exception in motion state:

| Key Binding | Description                              |
|-------------+------------------------------------------|
| ~H~         | Scroll cursor to top of window           |
| ~K~         | Scroll cursor to bottom  of window       |
| ~L~         | Lookup documentation of element at point |
|             |                                          |

** Related efforts
Other people have asked on the Spacemacs issue tracker how to remap HJKL.

- [[https://github.com/syl20bnr/spacemacs/issues/1250][#1250]] suggests to use ~define-key~.
- [[https://github.com/syl20bnr/spacemacs/issues/1391][#1391]] is trying to remap HJKL in micro-states. syl20 suggests using
  ~advice-around~, because rebuilding all packages to support HJKL swapping
  might not be worth it.
- [[https://github.com/syl20bnr/spacemacs/issues/2443][#2443]] raises the issue for Dvorak layouts.  [[https://github.com/jbranso/evil-dvorak/blob/master/evil-dvorak.el][evil-dvorak]] is mentioned as
  changing too much bindings.  The issue goes nowhere after people suggest to
  accept HJKL.
- [[https://github.com/syl20bnr/spacemacs/issues/3018][#3018]] asks for the right way to do it.  syl20 suggests ~key-translation-map~
  (see [[info:elisp#Translation%20Keymaps][Translation Keymaps]]).

[[https://github.com/jbranso/evil-dvorak/blob/master/evil-dvorak.el][evil-dvorak]] defines a global minor mode with a custom keymap.  Adds hooks for
web-mode, where it redefines the bindings.  Global minor mode means you can
toggle it dynamically, but unless you hand your keyboard to someone, this is of
little advantage.  Via a layer, you can just comment it and reload Spacemacs.
