#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# Make sure this is before the 'exec' command or it won't be sourced.
[ -f /etc/xprofile ] && source /etc/xprofile
[ -f ~/.xprofile ] && source ~/.xprofile

export DE=xfce
export PATH="${PATH}:/home/samim/.bin"

autorandr -c

/home/samim/.bin/keyboard_configure.sh
perWindowLayoutD

# Disable touchpad taps while typing
syndaemon -t -k -i 1 &

# Set background
[ -e ~/.fehbg ] && source ~/.fehbg

# Hide mouse when not used
unclutter &

# dunst &

# Picom window compositor
/usr/bin/picom -b --config ~/.picom &

# screen powersave
xset +dpms
xset dpms 0 0 300

# Automount disks
thunar --daemon &

greenclip daemon &

xrdb -merge ~/.Xresources

# trayer --edge top --align right --SetDockType true --SetPartialStrut true \
#   --expand true --width 8 --transparent true --alpha 85 --tint 0x00000000 --height 20 \
#   --monitor 0 &

# nm-applet &
# blueman-applet &
redshift-gtk &
# xfce-power-manager & 
# kdeconnect-indicator &
# eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets)
# pasystray &
synclient TapButton1=1

# exec xmonad
exec startxfce4
