#!/bin/sh
if [[ -n "$1" ]]
then
	emacsclient -c --socket-name="/tmp/samim/emacs1000/server/server" -e '(psamim-set-window-fonts)' "$1"
else
	emacsclient -c --socket-name="/tmp/samim/emacs1000/server/server" -e '(psamim-set-window-fonts)'
fi

