#!/bin/bash

notify-send "Switched to docked mode"
/home/samim/.bin/hdmi-sound-toggle
# /home/samim/.bin/launch_polybar
/home/samim/.bin/keyboard-configure
echo 'awesome.restart()' | awesome-client
systemctl --user restart feh-wallpaper
