# load zgen  -*- mode: sh; -*-
source "${HOME}/.dotfiles/zgen/zgen.zsh"

# check if there's no init script
if ! zgen saved; then
    echo "Creating a zgen save"

    zgen oh-my-zsh

    # plugins
    zgen oh-my-zsh plugins/git
    zgen oh-my-zsh plugins/git-extras
    zgen oh-my-zsh plugins/pass
    zgen oh-my-zsh plugins/archlinux
    zgen oh-my-zsh plugins/vi-mode
    zgen oh-my-zsh plugins/extract
    zgen oh-my-zsh plugins/golang
    zgen oh-my-zsh plugins/gradle
    zgen oh-my-zsh plugins/sudo
    zgen oh-my-zsh plugins/docker
    zgen oh-my-zsh plugins/fasd
    zgen oh-my-zsh plugins/nmap
    zgen oh-my-zsh plugins/last-working-dir
    zgen oh-my-zsh plugins/themes
    zgen oh-my-zsh plugins/mosh
    zgen oh-my-zsh plugins/cp
    zgen oh-my-zsh plugins/common-aliases
    zgen oh-my-zsh plugins/history-substring-search
    zgen load zsh-users/zsh-syntax-highlighting
    zgen load zsh-users/zaw
    zgen load zsh-users/zsh-completions src
    zgen load zsh-users/zsh-autosuggestions
    zgen load changyuheng/zsh-interactive-cd
    zgen load marzocchi/zsh-notify
    zgen load joel-porquet/zsh-dircolors-solarized
    zgen load djui/alias-tips
    zgen load Tarrasch/zsh-bd
    # zgen load larkery/zsh-histdb
    # zgen load lukechilds/zsh-nvm

    # theme
    zgen oh-my-zsh themes/agnoster

    # save all to init script
    zgen save
fi

_zsh_autosuggest_strategy_histdb_top_here() {
    local query="select commands.argv from
history left join commands on history.command_id = commands.rowid
left join places on history.place_id = places.rowid
where places.dir LIKE '$(sql_escape $PWD)%'
and commands.argv LIKE '$(sql_escape $1)%'
group by commands.argv order by count(*) desc limit 1"
    suggestion=$(_histdb_query "$query")
}

# ZSH_AUTOSUGGEST_STRATEGY=histdb_top_here

# Zaw
zstyle ':filter-select' max-lines 4 # use $LINES - 4 for filter-select
zstyle ':filter-select' case-insensitive yes # enable case-insensitive search

bindkey '^R' zaw-history
bindkey -M filterselect '^R' down-line-or-history
bindkey -M filterselect '^S' up-line-or-history
bindkey -M filterselect '^E' accept-search
bindkey '^P' zaw-process
bindkey '^F' zaw-open-file
bindkey '^[^M' autosuggest-execute

export JAVA_HOME=/usr/lib/jvm/default
export DEFAULT_USER="samim"
export GOPATH="$HOME/.go"
export ANDROID_HOME="/media/hdd/android-sdk/"
export EDITOR=emct
export ANDROID_EMULATOR_USE_SYSTEM_LIBS=1
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=242"
export PYENV_ROOT="$HOME/.pyenv"
export LEDGER_FILE="$HOME/Notes/ledger.ledger"

alias e=$EDITOR
alias down="aria2c --conf-path=${HOME}/.aria2/down.conf"
alias bdown="aria2c --conf-path=${HOME}/.aria2/bersam.conf"
alias tdown="aria2c --all-proxy=http://127.0.0.1:7777 --conf-path=${HOME}/.aria2/down.conf"
alias rdown="aria2c --enable-rpc --rpc-listen-port=6800 --rpc-listen-all=true --conf-path=${HOME}/.aria2/down.conf"
alias fly='sshuttle  --dns -r 52565751e0b8cd99d30001ba@private-psamim.rhcloud.com 0/0'
alias o='xdg-open'
alias xclip='xclip -selection clipboard'
alias j='fasd_cd -d'
alias jj='fasd_cd -d -i'
alias tmux='direnv exec / tmux'

export PATH=$PATH:$HOME/.cabal/bin
export PATH=$HOME/.bin:$PATH
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools:$ANDROID_HOME/tools
export PATH=$PATH:$JAVA_HOME/bin
export PATH=$PYENV_ROOT/bin:$PATH
export PATH=$HOME/.yarn/bin:$PATH

eval "$(direnv hook zsh)"
# eval $(keychain --eval --quiet)
# eval "$(pyenv init -)"



[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
